#+TITLE: Section 11
#+SUBTITLE: Files
#+AUTHOR: Mohammed Asir Shahid
#+EMAIL: MohammedShahid@protonmail.com
#+DATE: 2021-08-04

* Filenames and Absolute/Relative File Paths

We'll learn about files, folders, and how Python can work with them.

If we want our data to persist after our program is finished, we need to save it to a file.

** Fileames and File Paths

Each of our files has 2 key properties. The file name and the file path.

** os module

The os module contains numerous file path related functions that we can use.

*** os.getcwd()

Every program has a setting called the current working directory, this tells us the directory that we are currently in. We can use the getcwd() function in order to find our current working directory.

#+begin_src python :results output :exports both

import os

print(os.getcwd())

#+end_src

#+RESULTS:
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files

*** os.chdir()

We can also change the current working directory using this chdir() function.

#+begin_src python :results output :exports both

import os

print(os.getcwd())

os.chdir("/")

print(os.getcwd())

#+end_src

#+RESULTS:
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files
: /

** Absolute and Relative Paths

There are two kinds of file paths, relative and absolute. The absolute file path begins with the root directory and gives you the complete location of the file. A relative file path is relative to the current working directory.

** . and .. Folders

These are not real directories, but they can be used with relative paths. The single dot stands for this directory while two dots stands for the paret directory, the directory that your current working directory is in.

** os.path module
*** os.path.join()

This is a join function inside of a path module inside of an os module. It takes several string arguments and returns a string value of a path for the os that you are using.

#+begin_src python :results output :exports both

import os
print(os.path.join("folder1","folder2","folder3","file.png"))

#+end_src

#+RESULTS:
: folder1/folder2/folder3/file.png

*** os.path.abspath()

The abspath() function will return the absolute path of the path that you pass it.

#+begin_src python :results output :exports both

import os

print(os.path.abspath("Section 11.org"))


#+end_src

#+RESULTS:
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org

*** os.path.isabs()

The isabs() function is a way to determine if a given path is absolute.

#+begin_src python :results output :exports both

import os

print(os.path.abspath("Section 11.org"))

print(os.path.isabs("Section 11.org"))

print(os.path.abspath("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

print(os.path.isabs("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

#+end_src

#+RESULTS:
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org
: False
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org
: True

*** os.path.relpath()

This function will give you the relative path between two paths. The first argument is the file/directory we want to get to and the second is the directory we are already in.



#+begin_src python :results output :exports both

import os

print(os.path.relpath("Section 11.org", "/usr/bin"))

print(os.path.relpath("Section 11.org", "/home/mohammeds/"))


#+end_src

#+RESULTS:
: ../../home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org
: Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org

*** os.path.dirname()

This function pulls out just the directory part of the path.

#+begin_src python :results output :exports both

import os

print(os.path.dirname("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

#+end_src

#+RESULTS:
:
: /home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files

*** os.path.basename()

This function pulls out just the last part of the path. Either the filename or just the directory itself if there is no file in the path.

#+begin_src python :results output :exports both

import os

print(os.path.basename("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

#+end_src

#+RESULTS:
: Section 11.org

*** os.path.exists()

This function can check and see if the path you are passing actually exists.

#+begin_src python :results output :exports both

import os

print(os.path.exists("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

print(os.path.exists("/home/mohammeds/Fake File Path"))

#+end_src

#+RESULTS:
: True
: False

*** os.path.isfile()

We can use this function to see if what we pass to it is a file or not.

#+begin_src python :results output :exports both

import os

print(os.path.isfile("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

print(os.path.isfile("/home/mohammeds/Fake File Path"))

#+end_src

#+RESULTS:
: True
: False

*** os.path.isdir()

We can use this function to see if what we pass to it is a directory or not.

#+begin_src python :results output :exports both

import os

print(os.path.isdir("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

print(os.path.isdir("/home/mohammeds/"))

#+end_src

#+RESULTS:
: False
: True

*** os.path.getsize()

This function gives us the size of the file in bytes.

#+begin_src python :results output :exports both

import os

print(os.path.getsize("/home/mohammeds/Documents/Automate the Boring Stuff/Section 11: Files/Section 11.org"))

#+end_src

#+RESULTS:
: 5781

** os.listdir()

This function isn't in the path module. It can be passed a file path of a folder and then it'll return a list of strings of the filenames and folder names that it contains.

#+begin_src python :results output :exports both

import os

print(os.listdir("/home/mohammeds/Documents"))

#+end_src

#+RESULTS:
: ['[Chapman and Hall_CRC the R Ser] Albert, Jim_ Baumer, Benjamin S._ Marchi, Max - Analyzing Baseball Data with R (2018, Chapman and Hall_CRC) - libgen.lc.pdf', 'bedrock-linux-0.7.20beta1-x86_64.sh', 'fstab.txt', 'Verify Payment.pdf', 'mission-369-advanced-regular-expressions-takeaways.pdf', 'userguide.pdf', 'Quidditch Through the Ages - J.K. Rowling.pdf', 'Resume', 'SmashCharacters.txt', 'LFS-BOOK-10.1.pdf', 'Linux From Scratch - Version 10.1 - LFS-BOOK-10.1.pdf', 'Oathbringer_ Book Three of the Stormlight Archive_B01NAWAH85.kfx', 'Andrew Ng Machine Learning Lectures', 'Hugo Websites', 'Data Scientist in Python DataQuest', 'mohammed-shahid-python-for-data-science-fundamentals.pdf', 'README.md', '.git', 'mkdir', 'Crypto Trading Bot', 'Machine Trading', 'The Home Depot - Order Confirmation.pdf', 'Online Return Center.pdf', 'LeetCode', 'Kaggle', 'Coursera', 'Data Analyst in R DataQuest', 'edX', 'org-basics.org', 'happybday.org', 'org', 'letter.org', 'AB_NYC_2019.csv', 'cse351_hw1_fazli_faraz_110018236.ipynb', '.ipynb_checkpoints', 'mariaradio.org', '.auctex-auto', 'mariaradio.tex', 'mariaradio.pdf', 'mariaradio.md', 'mariaradio.html', 'Order Confirmation _ Law School Admission Council.pdf', 'marialetter.org', 'Automate the Boring Stuff', 'TEKgence Application Form.xlsx', '.dir-locals.el']

** Example Code: Finding the total size of all files in a folder.

#+begin_src python :results output :exports both

import os

totalSize=0

for file in os.listdir("/home/mohammeds/Documents"):
    if not os.path.isfile(os.path.join("/home/mohammeds/Documents", file)):
        continue
    totalSize+=os.path.getsize(os.path.join("/home/mohammeds/Documents", file))

print(totalSize)

#+end_src

#+RESULTS:
: 382371482

** os.makedirs()

This function can create directories for you.

#+begin_src python :results output :exports both

import os

print(os.getcwd())

print(os.listdir())

os.makedirs("TestDir")

print(os.listdir())

#+end_src

* Reading and Writing Plaintext Files

We can start writing strings to files that we create in order to save information. We can then read this data with Python.

** Plaintext and Binary Files

Plaintext files only contain basic text characters and don't include information about color or font. Often times they have .txt extensions. Python scripts are also plain text files, except they use the .py file extension.

They can be opened with text editors such as Emacs.

Binary files are all other types of files. PDF, JPG, PNG, etc. When you open these with a text editor, it will be impossible to understand.

** Reading or Writing Files in Python

There are three main steps for reading and writing files in Python.

*** The open() Function

This function opens files.

#+begin_src python :results output :exports both

open("hello.txt")

#+end_src

#+RESULTS:

***  Read Mode

The open() function opens the file in read mode. This only lets you read the data, it does not let you modify it.

***  The read() method

This method lets you read the opened file.

***  The close() method

This method closes the opened file. If you want to continue accessing it, you should save it to a variable.

#+begin_src python :results output :exports both

helloFile=open("hello.txt")


content=helloFile.read()

print(content)

helloFile.close()

#+end_src

#+RESULTS:
: Hello!
:

*** The readlines() Method

This method returns all of the lines as strings within a list.

#+begin_src python :results output :exports both

helloFile=open("hello.txt")
content=helloFile.readlines()

print(content)

#+end_src

#+RESULTS:
: ['Hello!\n']

*** Write mode

In order to write to a file, it needs to be opened in write or append mode. This can overwrite existing files. For write mode, you can pass in a "w" argument to the open() function.

#+begin_src python :results output :exports both

helloFile=open("hello2.txt","w")
helloFile.write("Hello!!!!")

#+end_src

#+RESULTS:

*** Append mode

In order to write to a file, it needs to be opened in write or append mode. This can overwrite existing files. For append mode, you can pass in a "a" argument to the open() function.

#+begin_src python :results output :exports both

helloFile=open("hello.txt", "a")
helloFile.write("How are you?")

#+end_src

#+RESULTS:

*** Example

#+begin_src python :results output :exports both


baconFile=open("bacon.txt", "w")

baconFile.write("Bacon is not a vegetable")
baconFile.close()

baconFile=open("bacon.txt")

print(baconFile.read())

#+end_src

#+RESULTS:
: Bacon is not a vegetable

** The shelve Module

Writing and reading text files is a good way to store single long strings, but if we want to save more complex data structures like lists and dictionaries, then we can save Python programs to binary shelve files.

*** The shelve.open() Method

This method can open shelve files.

#+begin_src python :results output :exports both

import shelve

shelfFile=shelve.open("mydata")
shelfFile["cats"]=["Zophie","Pooka","Simon","Fat-tail","Cleo"]
shelfFile.close()

shelfFile=shelve.open("mydata")
print(shelfFile["cats"])

#+end_src

#+RESULTS:
: ['Zophie', 'Pooka', 'Simon', 'Fat-tail', 'Cleo']

The benefit of using the shelve module is that you can store lists, dictionaries, and non text data and then reopen them in the future.

*** The keys() and values() Shelf Methods

Shelf file objects are very similar to dictionaries in the sense that they have keys and values.

#+begin_src python :results output :exports both

import shelve

shelfFile=shelve.open("mydata")

print(shelfFile.keys())
print(shelfFile.values())


print(list(shelfFile.keys()))
print(list(shelfFile.values()))

shelfFile.close()
#+end_src
* Copying and Moving Files and Folders

We can also organize files on our drive using Python.

** Shell Utilities Module

This module has functions that let us copy, rename, and delete files in Python programs.

*** shutil.copy() Function

This function lets us copy files in Python. We can either copy and leave the filename or copy and give a new file name.

#+begin_src python :results output :exports both

import shutil,os

shutil.copy("hello2.txt", "TestDir")

shutil.copy("hello2.txt", "TestDir/newhello2.txt")

print(os.listdir("TestDir"))

#+end_src

#+RESULTS:
: ['hello2.txt', 'newhello2.txt']

*** shutil.copytree() Function

The copy function works for single files, but what if we want to copy an entire folder? Then we can use the copytree function.


#+begin_src python :results output :exports both

import shutil,os

shutil.copytree("TestDir","TestDirBackup")

#+end_src

#+RESULTS:

#+begin_src python :results output :exports both

import shutil,os

print(os.listdir("TestDirBackup"))

#+end_src

#+RESULTS:
: ['hello2.txt', 'newhello2.txt']

*** shutil.move() function

This can be used for moving and renaming files. If you want to rename a file, you can move it to the same directory using the move() function and then change the filename.

#+begin_src python :results output :exports both

import shutil,os

shutil.move("TestDirBackup/newhello2.txt", ".")

print(os.listdir("TestDirBackup"))

#+end_src

#+RESULTS:
: ['hello2.txt']

* Deleting Files

There are three functions that we can use for deleting files.

** Deleting Functions

*** os.unlink() (Deletes a single file.)

#+begin_src python :results output :exports both

import os

os.unlink("hello2.txt")


#+end_src

#+RESULTS:

#+begin_src python :results output :exports both

import os

print(os.listdir())

#+end_src

#+RESULTS:
: ['.gitkeep', 'Section 11.org', '.auctex-auto', 'Section 11.tex', 'Section 11.pdf', 'Section 11.md', 'udemy-automate-boring-python-lesson-30.mp4', 'udemy-automate-boring-python-lesson-31.mp4', 'udemy-automate-boring-python-lesson-32.mp4', 'udemy-automate-boring-python-lesson-33.mp4', 'udemy-automate-boring-python-lesson-34.mp4', 'TestDir', 'hello.txt', 'bacon.txt', 'mydata', 'TestDirBackup', 'newhello2.txt']

*** os.rmdir() (Delete an empty folder)

This function only removes directories that are completely empty. If the directory you try to delete has data, Python will return an error.

*** shutil.rmtree() (Deletes a folder and its entire contents)

This is the delete analog of the copytree() function.

#+begin_src python :results output :exports both

import os,shutil

shutil.rmtree("TestDirBackup")

print(os.listdir())

#+end_src

#+RESULTS:
: ['.gitkeep', 'Section 11.org', '.auctex-auto', 'Section 11.tex', 'Section 11.pdf', 'Section 11.md', 'udemy-automate-boring-python-lesson-30.mp4', 'udemy-automate-boring-python-lesson-31.mp4', 'udemy-automate-boring-python-lesson-32.mp4', 'udemy-automate-boring-python-lesson-33.mp4', 'udemy-automate-boring-python-lesson-34.mp4', 'TestDir', 'hello.txt', 'bacon.txt', 'mydata', 'newhello2.txt']

** Dry Run

These deleting functions can be dangerous, so in order to make sure nothing goes wrong, we should do a dry run when using them.

Here we would comment out any line containing deleting functions and then instead printing out the files that we were trying to delete. This can help us make sure that we are not deleting the wrong thing.

#+begin_src python :results output :exports both

import os,shutil

os.chdir("/home/mohammeds/Documents")

for filename in os.listdir():
    if filename.endswith(".rxt"):
#        os.unlink(filename)
        print(filename)

#+end_src

#+RESULTS:

** The send2trash Module

These deleting functions are still dangerous, even when doing a dry run since they will be deleted permanently. Instead, we can use the send2trash module's functions which sends the files to the recycling bin.

We need to install it using pip.

#+begin_src bash
pip install send2trash
#+end_src

#+RESULTS:
| Defaulting  | to      | user       | installation | because | normal                           | site-packages | is | not | writeable |
| Requirement | already | satisfied: | send2trash   | in      | /usr/lib/python3.9/site-packages | (1.4.2)       |    |     |           |

#+begin_src python :results output :exports both

import send2trash

send2trash.send2trash("bacon.txt")

#+end_src

#+RESULTS:
